domain_path: E:\02_Projects\02_Vitis_workspace\01_freertos_platform\export\01_freertos_platform\sw\freertos_ps7_cortexa9_0
app_src_dir: E:\01_DevTools\01_Vitis\2025.1\Vitis\data\embeddedsw\lib\sw_apps\freertos_hello_world
template: freertos_hello_world
lang: c
